# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('allow_group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
