# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('command', models.CharField(max_length=300)),
                ('who', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('allow_group', models.CharField(max_length=20)),
                ('hostname', models.CharField(default='localhost', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(default='hello', max_length=20, verbose_name='\u5bc6\u7801')),
                ('group', models.CharField(max_length=20, verbose_name='\u7ec4')),
                ('tel', models.CharField(max_length=20, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(max_length=254, null='non')),
            ],
        ),
    ]
