# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunwei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('install_root', models.CharField(max_length=20)),
                ('zipfile', models.FileField(upload_to='zipfile')),
            ],
        ),
        migrations.RenameField(
            model_name='server',
            old_name='allow_group',
            new_name='own_group',
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
