# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunwei', '0002_auto_20170614_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='localhost', max_length=20),
        ),
    ]
