# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='filename',
            field=models.FileField(upload_to='myfile'),
        ),
    ]
