# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170527_0959'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myfile',
            table=None,
        ),
    ]
