# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to=b'picture'),
        ),
    ]
