# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170613_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=20)),
            ],
        ),
    ]
