# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='sql',
            field=models.FileField(null=True, upload_to=b'mysql'),
        ),
    ]
